INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   225
        Validation size: 25
        Checkpoints:     True
        Device:          cpu
        Images scaling:  0.5
        Mixed Precision: False
Epoch 1/5:   0%|                                       | 0/225 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "/home/inge/Pytorch-UNet/train.py", line 183, in <module>
    train_net(net=net,
  File "/home/inge/Pytorch-UNet/train.py", line 80, in train_net
    for batch in train_loader:
  File "/home/inge/anaconda3/envs/unet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/inge/anaconda3/envs/unet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/inge/anaconda3/envs/unet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/inge/anaconda3/envs/unet/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/inge/anaconda3/envs/unet/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/inge/anaconda3/envs/unet/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/inge/anaconda3/envs/unet/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/inge/anaconda3/envs/unet/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 311, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/inge/Pytorch-UNet/utils/data_loading.py", line 61, in __getitem__
    assert len(mask_file) == 1, f'Either no mask or multiple masks found for the ID {name}: {mask_file}'
AssertionError: Either no mask or multiple masks found for the ID painting299: []